  
const dummyNFTs = [
    {index: 1,  name: 'NFT £1', owner: 'John', price: 0.02, category: 'arts', image: '/image_1.jpg'},
    {index: 2,name: 'NFT £2', owner: 'Lucy', price: 0.07, category: 'gaming' ,image: '/image_2.jpg'},
    {index: 3, name: 'NFT £3',owner: 'Mark', price: 0.04, category: 'photography', image: '/image_3.jpg'},
    {index: 4, name: 'NFT £4', owner: 'John', price: 0.20, category: 'arts', image: '/image_4.jpg'},
    {index: 5, name: 'NFT £5', owner: 'David',  price: 0.05, category: 'exhibition',image: '/image_5.jpg'},
    {index: 6, name: 'NFT £6', owner: 'Mary', price: 0.01, category: 'membership', image: '/image_7.jpg'},
    {index: 7, name: 'NFT £7', owner: 'Larry', price: 0.10, category: 'gaming', image: '/image_8.jpg'},
    {index: 8, name: 'NFT £8', owner: 'Lucy', price: 0.03, category: 'arts', image: '/image_9.jpg'},
    {index: 9, name: 'NFT £9', owner: 'Mark', price: 0.04, category: 'photography', image: '/image_10.jpg'},
    {index: 10, name: 'NFT £10', owner: 'Larry', price: 0.03, category: 'gaming', image: '/image1.jpg'},
    {index: 11, name: 'NFT £11', owner: 'John', price: 0.02, category: 'arts', image: '/image2.jpg'},
    {index: 12, name: 'NFT £12', owner: 'Lucy', price: 0.12, category: 'photography', image: '/image3.jpg'},
    {index: 13, name: 'NFT £13', owner: 'James', price: 0.21, category: 'arts',image: '/image4.jpg'},
    {index: 14, name: 'NFT £14', owner: 'Mark', price: 0.17, category: 'gaming', image: '/image5.jpg'},
    {index: 15, name: 'NFT £15', owner: 'Mary', price: 0.15, category: 'photography',  image: '/image6.jpg'},
    {index: 16, name: 'NFT £16', owner: 'John', price: 0.02, category: 'arts', image: '/image11.jpg'},
    {index: 17, name: 'NFT £17', owner: 'Mark', price: 0.05, category: 'exhibition', image: '/image12.jpg'},
    {index: 18, name: 'NFT £18', owner: 'Mary', price: 0.02, category: 'membership', image: '/image16.jpg'},
    {index: 19, name: 'NFT £19', owner: 'James', price: 0.04, category: 'arts', image: '/image17.jpg'},
    {index: 20, name: 'NFT £20', owner: 'David', price: 0.10, category: 'exhibition', image: '/image18.jpg'},
    {index: 21, name: 'NFT £21', owner: 'John', price: 0.20, category: 'gaming', image: '/image19.jpg'},
    {index: 22, name: 'NFT £22', owner: 'Lucy', price: 0.04, category: 'arts', image: '/image20.jpg'},
    {index: 23, name: 'NFT £23', owner: 'Mary', price: 0.22, category: 'gaming', image: '/image21.jpg'},
    {index: 24, name: 'NFT £24', owner: 'Mark', price: 0.06, category: 'arts', image: '/image22.jpg'},
    {index: 25, name: 'NFT £25', owner: 'Mary', price: 0.09, category: 'photography', image: '/image23.jpg'},
    {index: 26, name: 'NFT £26', owner: 'James', price: 0.08, category: 'gaming', image: '/image24.pjg'},
    {index: 27, name: 'NFT £27', owner: 'Lucy', price: 0.06, category: 'exhibition', image: '/image_1.jpg'},
    {index: 28, name: 'NFT £28', owner: 'Mary', price: 0.07, category: 'photography', image: '/image_2.jpg'},
    {index: 29, name: 'NFT £29', owner: 'John', price: 0.02, category: 'membership', image: '/image_3.jpg'},
    {index: 30, name: 'NFT £30', owner: 'James', price: 0.24, category: 'gaming', image: '/image_4.jpg'},
    {index: 31, name: 'NFT £31', owner: 'John', price: 0.22, category: 'exhibition', image: '/image_5.jpg'},
    {index: 32, name: 'NFT £32', owner: 'Mark', price: 0.16, category: 'gaming', image: '/image_7.jpg'},
    {index: 33, name: 'NFT £33', owner: 'John', price: 0.17, category: 'photography', image: '/image_8.jpg'},
    {index: 34, name: 'NFT £34', owner: 'John', price: 0.17, category: 'photography', image: '/image_8.jpg'},
    {index: 35, name: 'NFT £35', owner: 'Lucy', price: 0.14, category: 'arts', image: '/image_9.jpg'},
    {index: 36, name: 'NFT £36', owner: 'Mary', price: 0.15, category: 'arts', image: '/image_10.jpg'},
    {index: 37, name: 'NFT £37', owner: 'Lucy', price: 0.12, category: 'gaming', image: '/image1.jpg'},
    {index: 38, name: 'NFT £38', owner: 'Lucy', price: 0.07, category: 'membership', image: '/image2.jpg'},
    {index: 39, name: 'NFT £39', owner: 'John', price: 0.04, category: 'gaming', image: '/image3.jpg'},
    {index: 40, name: 'NFT £40', owner: 'Lucy', price: 0.05, category: 'photography', image: '/image4.jpg'},
    {index: 41, name: 'NFT £41', owner: 'Mark', price: 0.14, category: 'membership', image: '/image5.jpg'},
    {index: 42, name: 'NFT £42', owner: 'Lucy', price: 0.16, category: 'exhibition', image: '/image6.jpg'},
    {index: 43, name: 'NFT £43', owner: 'Lucy', price: 0.16, category: 'exhibition', image: '/image6.jpg'},
    {index: 44, name: 'NFT £44', owner: 'James', price: 0.13, category: 'gaming', image: '/image11.jpg'},
    {index: 45, name: 'NFT £45', owner: 'David', price: 0.07, category: 'exhibition', image: '/image12.jpg'},
    {index: 46, name: 'NFT £46', owner: 'David', price: 0.09, category: 'photography', image: '/image16.jpg'},
    {index: 47, name: 'NFT £47', owner: 'James', price: 0.12, category: 'gaming', image: '/image17.jpg'},
    {index: 48, name: 'NFT £48', owner: 'Lucy', price: 0.14, category: 'exhibition', image: '/image18.jpg'},
    {index: 49, name: 'NFT £49', owner: 'John', price: 0.16, category: 'exhibition', image: '/image19.jpg'},
    {index: 50, name: 'NFT £50', owner: 'Mary', price: 0.18, category: 'membership', image: '/image20.jpg'},
    {index: 51, name: 'NFT £51', owner: 'Lucy', price: 0.16, category: 'pfps', image: '/image6.jpg'},
    {index: 52, name: 'NFT £52', owner: 'James', price: 0.13, category: 'pfps', image: '/image11.jpg'},
    {index: 53, name: 'NFT £53', owner: 'David', price: 0.07, category: 'pfps', image: '/image12.jpg'},
    {index: 54, name: 'NFT £54', owner: 'David', price: 0.09, category: 'pfps', image: '/image16.jpg'},
    {index: 55, name: 'NFT £55', owner: 'James', price: 0.12, category: 'pfps', image: '/image17.jpg'},
    {index: 56, name: 'NFT £56', owner: 'Lucy', price: 0.14, category: 'pfps', image: '/image18.jpg'},
    {index: 57, name: 'NFT £57', owner: 'John', price: 0.16, category: 'pfps', image: '/image19.jpg'},
    {index: 58, name: 'NFT £58', owner: 'Mary', price: 0.18, category: 'pfps', image: '/image20.jpg'},
    
    
   ]

   module.exports = dummyNFTs